### ISSUE TITLE
Any release of these? Linux support with mono??

### ISSUE THREAD

**Issue by ghost** [DualBrain/Solitaire#1]

**Comment by DualBrain** [comment]
Until now, I really haven't considered this as a project that would be cross platform; however, with that said... does sound interesting. Might have to consider the options now that things are fully ported to .NET 8. ;-)

**Comment by DualBrain** [comment]
Dropping in to update that I've added an *official* release (after getting it current-ish). As for cross platform, this may be considered in the future; possibly by porting the code to vbPixelGameEngine - which you can check out at https://github.com/DualBrain/vbPixelGameEngine. I recently was able to get that project to the point where the same code can execute on Windows and Linux, so as that project progresses it might make sense at some point to do so. For now, closing this ticket and will consider it in the future.
